spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: pass
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: debug
