spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root # schedule
    password: pass # s3cret!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중: update, 제출 전: validate 권장 create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul
jwt:
  secret: "randoms3cretkey_example_aaaaaah1201931randoms3cretkey_example_aaaaaah1201931"
  access-token-validity-ms: 3600000 # 1 hour
  refresh-token-validity-ms: 1209600000 # 14일이었나
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080
